services:
  web:
    image: ghcr.io/consolidate-software/consolidate-web:${VERSION}
    user: root

    volumes:
      - cache:/cache
      - config:/config
      - ./backup:/backup

    env_file: 
      - path: ".env"
        required: false

    environment:
      ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT:-Production}"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "${FORWARDEDHEADERS_ENABLED:-false}"
      HTTP_PORTS: "${HTTP_PORT}"
      HTTPS_PORTS: "${HTTPS_PORT}"
      DatabasePort: "${DATABASE_PORT}"

      AdminEmail: "${ADMIN_EMAIL}"
      AdminPassword: "${ADMIN_PASSWORD}"

      License__LicenseKey: "${LICENSE_KEY}"

      Database__Name: "${DATABASE_NAME}"
      Database__CertificatePath: "/config/client/${DATABASE_NAME}.pfx"
      Database__CertificatePassword: "${DATABASE_CERT_PASSWORD}"
      Database__Urls__0: "https://db:8080"
      Database__ValidateRemoteCertificate: "false"

      services__collaboration__http__0: "http://collab:5123"
      services__collabora__https__0: "${COLLABORA_URL}"
      ConnectionStrings__redis: "cache:6379"

      LettuceEncrypt__Enabled: "${HTTPS_PORT:+true}"
      LettuceEncrypt__StorageDirectory: "/config/acme"
      LettuceEncrypt__StoragePassword: "${DATABASE_CERT_PASSWORD}"
      LettuceEncrypt__AcceptTermsOfService: "true"
      LettuceEncrypt__DomainNames__0: "${DOMAIN_NAME}"
      LettuceEncrypt__EmailAddress: "${ADMIN_EMAIL}"
      
      Backup__FolderPath: "/backup"

    ports:
      - "${HTTP_PORT:-80}:${HTTP_PORT:-80}"
      - "${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      - "${DATABASE_PORT:-8080}:${DATABASE_PORT:-8080}"

    networks:
      app-network:
        aliases:
          - "${DOMAIN_NAME}"

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      db_setup:
        condition: service_completed_successfully

  collab:
    image: ghcr.io/consolidate-software/consolidate-collab:${VERSION}

    environment:
      PORT: "5123"
      services__api__http__0: "${HTTP_PORT:+http://web:${HTTP_PORT}}"
      services__api__https__0: "${HTTPS_PORT:+https://${DOMAIN_NAME}:${HTTPS_PORT}}"

    networks:
      - app-network

    restart: unless-stopped

  cache:
    image: redis:8.0.3

    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

    networks:
      - app-network

    restart: unless-stopped

  db:
    image: ghcr.io/consolidate-software/consolidate-db:${VERSION}
    user: root

    volumes:
      - data:/var/lib/ravendb/data
      - config:/config
      - ./backup:/backup

    environment:
      CERTIFICATE_BASE_DIR: "/config"
      CERTIFICATE_PASSWORD: "${DATABASE_CERT_PASSWORD}"
      DOMAIN_NAME: "${DOMAIN_NAME}"
      RAVEN_License: "${DATABASE_LICENSE}"
      RAVEN_License_Eula_Accepted: "true"
      RAVEN_PublicServerUrl: "https://db:8080"

    networks:
      - app-network

    restart: unless-stopped

  db_setup:
    image: ghcr.io/consolidate-software/consolidate-setup:${VERSION}
    user: root

    volumes:
      - config:/config

    environment:
      CERTIFICATE_BASE_DIR: "/config"
      DATABASE_URL: "https://db:8080"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_CERT_PASSWORD: "${DATABASE_CERT_PASSWORD}"

    networks:
      - app-network

    restart: no

    depends_on:
      db:
        condition: service_healthy

volumes:
  data:
  cache:
  config:

networks:
  app-network:
